version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:5100"

    volumes:
      - ./logs:/app/logs     
      - ./uploads:/app/uploads  

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
