apiVersion: v1
kind: Service
metadata:
  name: py-bg-remover
  labels:
    app: py-bg-remover
spec:
  type: LoadBalancer
  ports:
  - port: 5100
    targetPort: 5100
  selector:
    app: py-bg-remover